### ISSUE TITLE
Out of Memory Error

### ISSUE THREAD

**Issue by RAMENtheNOODLES** [acmerobotics/MeepMeep#13]
When I attempt to run Meep Meep, I keep getting an Out of Memory Error. I tried increasing the amount of memory allocated towards it, but I could not get it to work.

Here is my code:
``` java
package spudnik.team24288.meepmeeptesting;

import com.acmerobotics.roadrunner.Pose2d;
import com.acmerobotics.roadrunner.Vector2d;
import com.noahbres.meepmeep.MeepMeep;
import com.noahbres.meepmeep.roadrunner.DefaultBotBuilder;
import com.noahbres.meepmeep.roadrunner.entity.RoadRunnerBotEntity;

public class MeepMeepTesting {
    public static void main(String[] args) {
        MeepMeep meepMeep = new MeepMeep(800);

        RoadRunnerBotEntity myBot = new DefaultBotBuilder(meepMeep)
                // Set bot constraints: maxVel, maxAccel, maxAngVel, maxAngAccel, track width
                .setConstraints(60, 60, Math.toRadians(180), Math.toRadians(180), 15)
                .build();

        myBot.runAction(myBot.getDrive().actionBuilder(new Pose2d(7.00, -70.00, Math.toRadians(90.00)))
                .splineToConstantHeading(new Vector2d(7.00, -25.00), Math.toRadians(90.00))
                .splineTo(new Vector2d(7.00, -45.00), Math.toRadians(90.00))
                .splineToConstantHeading(new Vector2d(50.00, -35.00), Math.toRadians(90.00))
                .splineTo(new Vector2d(50.00, -60.00), Math.toRadians(-90.00))
                .splineToConstantHeading(new Vector2d(60.00, -60.00), Math.toRadians(90.00))
                .splineTo(new Vector2d(60.00, -35.00), Math.toRadians(90.00))
                .splineTo(new Vector2d(60.00, -60.00), Math.toRadians(-90.00))
                .splineTo(new Vector2d(48.00, -52.00), Math.toRadians(-90.00))
                .splineTo(new Vector2d(48.00, -70.00), Math.toRadians(-90.00))
                .splineTo(new Vector2d(7.00, -25.00), Math.toRadians(90.00)).build());

        meepMeep.setBackground(MeepMeep.Background.FIELD_INTO_THE_DEEP_OFFICIAL)
                .setDarkMode(true)
                .setBackgroundAlpha(0.95f)
                .addEntity(myBot)
                .start();
    }
}
```

And here is the error:
```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.base/java.lang.Double.valueOf(Double.java:632)
	at com.acmerobotics.roadrunner.Math.rangeCentered(Math.kt:60)
	at com.acmerobotics.roadrunner.Profiles.samplePathByRotation(Profiles.kt:651)
	at com.acmerobotics.roadrunner.Profiles.profile(Profiles.kt:673)
	at com.acmerobotics.roadrunner.TrajectoryBuilder.build(Builders.kt:849)
	at com.acmerobotics.roadrunner.TrajectoryActionBuilder.endTrajectory(Actions.kt:251)
	at com.acmerobotics.roadrunner.TrajectoryActionBuilder.build(Actions.kt:766)
	at spudnik.team24288.meepmeeptesting.MeepMeepTesting.main(MeepMeepTesting.java:31)
```

**Comment by rbrott** [comment]
Your path has some very sharp transitions that are messing with the numerics. Try making a smoother path.
